### ISSUE TITLE
sometimes reconnecting doesn't work

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#134]
My computer froze for a couple minutes, and mantaray printed this error:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/akuli/mantaray-prod/mantaray/backend.py", line 244, in _connect_and_recv_loop
    self._recv_loop()
  File "/home/akuli/mantaray-prod/mantaray/backend.py", line 399, in _recv_loop
    raise e
  File "/home/akuli/mantaray-prod/mantaray/backend.py", line 394, in _recv_loop
    line = _recv_line(sock, self._recv_buffer)
  File "/home/akuli/mantaray-prod/mantaray/backend.py", line 174, in _recv_line
    raise OSError("Server closed the connection!")
OSError: Server closed the connection!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/akuli/mantaray-prod/mantaray/backend.py", line 250, in _connect_and_recv_loop
    self._disconnect()
  File "/home/akuli/mantaray-prod/mantaray/backend.py", line 472, in _disconnect
    sock.shutdown(socket.SHUT_RDWR)  # stops sending/receiving immediately
  File "/usr/lib/python3.9/ssl.py", line 1280, in shutdown
    super().shutdown(how)
OSError: [Errno 107] Transport endpoint is not connected
```

I couldn't reconnect without restarting mantaray.

**Comment by Akuli** [comment]
Currently there is only one `shutdown()` call, and it has the correct error handling.
