### ISSUE TITLE
MODE error

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#202]
On master, connecting to libera works but shows a couple errors on terminal:

```
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
Traceback (most recent call last):
  File "/home/akuli/mantaray/mantaray/backend.py", line 478, in _recv_loop
    self._handle_received_message(message)
  File "/home/akuli/mantaray/mantaray/backend.py", line 329, in _handle_received_message
    channel, mode_flags, nick = msg.args
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "/home/akuli/mantaray/mantaray/backend.py", line 478, in _recv_loop
    self._handle_received_message(message)
  File "/home/akuli/mantaray/mantaray/backend.py", line 329, in _handle_received_message
    channel, mode_flags, nick = msg.args
ValueError: not enough values to unpack (expected 3, got 2)
```

Should figure out what 2-argument `MODE` command means, or at least silence the error by checking if there's exactly 3 args.

**Comment by Akuli** [comment]
Now it happens with 4-argument `MODE`.

```
ERROR:root:error while handling event: MessageFromUser(sender_nick='litharge', sender_user_mask='litharge!litharge@libera/bot/litharge', command='MODE', args=['#libera', '-qo', '*!*@p200300ec8f304b9eddb3b5944e1f6030.dip0.t-ipconnect.de', 'litharge'])
Traceback (most recent call last):
  File "/home/akuli/mantaray-prod/mantaray/views.py", line 294, in _run_core
    received.handle_event(event, self)
  File "/home/akuli/mantaray-prod/mantaray/received.py", line 622, in handle_event
    _handle_received_message(server_view, event)
  File "/home/akuli/mantaray-prod/mantaray/received.py", line 555, in _handle_received_message
    _handle_mode(server_view, msg.sender_nick, msg.args)
  File "/home/akuli/mantaray-prod/mantaray/received.py", line 271, in _handle_mode
    channel, mode_flags, target_nick = args
ValueError: too many values to unpack (expected 3)
```
