### ISSUE TITLE
occasional error when closing mantaray

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#230]
Doesn't happen every time. Here's what it looks like when it does happen:

```
(env) akuli@akuli-desktop:~/mantaray$ python3 -m mantaray --alice --verbose
playsound is relying on another python subprocess. Please use `pip install pygobject` if you want playsound to run more efficiently.
Connect
Send: b'NICK Alice\r\n'
Send: b"USER AliceUsr 0 * :Alice's real name\r\n"
Recv: b':localhost 001 Alice :Welcome to Hircd v0.2, the ugliest IRC server in the world.\n'
Recv: b':localhost 376 Alice :End of MOTD command.\n'
Send: b'JOIN #autojoin\r\n'
Recv: b':Unknown TOPIC #autojoin :No topic\n'
Recv: b':Alice!AliceUsr@localhost JOIN :#autojoin\n'
Recv: b':localhost 353 Alice = #autojoin :Alice\n'
Recv: b':localhost 366 Alice #autojoin :End of /NAMES list\n'
Send: b'QUIT\r\n'
done event Quit()
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/akuli/mantaray/mantaray/__main__.py", line 110, in on_any_widget_focused
    irc_widget.get_current_view().mark_seen()
  File "/home/akuli/mantaray/mantaray/gui.py", line 165, in get_current_view
    [view_id] = self.view_selector.selection()
  File "/usr/lib/python3.9/tkinter/ttk.py", line 1422, in selection
    return self.tk.splitlist(self.tk.call(self._w, "selection"))
_tkinter.TclError: invalid command name ".!ircwidget.!treeview"
```

**Comment by Akuli** [comment]
No longer happens. #247 fixed this, according to `git bisect`.
